### ISSUE TITLE
Upload Debug Renderer to Modrinth

### ISSUE THREAD

**Issue by Insprill** [mworzala/mc_debug_renderer#16]
I'd love it if the client-side part of this mod could be uploaded to [Modrinth](https://modrinth.com/). It's nice to have all mods in one place, and when using Prism Launcher's auto-updater it's a little annoying having to dismiss the warning that it couldn't find Debug Renderer.

To make publishing easier, they have a Gradle plugin called [Minotuar](https://github.com/modrinth/minotaur) that allows you to publish releases and update the project page with simple Gradle tasks.

You could also use something like [mc-publish](https://github.com/Kir-Antipov/mc-publish) to automatically publish releases that are uploaded to GitHub.

**Comment by mworzala** [comment]
Yeah I may do this soon, I originally did not upload it anywhere because I was not planning on committing to keeping it updated. But it turns out its rather useful and I will likely keep updating it.

**Comment by mworzala** [comment]
Done [here](https://modrinth.com/mod/debug_renderer), pending review.
